# Generated by Django 5.2 on 2025-04-13 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0003_portfolioitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reward_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk_reward_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_calculations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
